name: 'Swarmpit Stack Destroy'
description: 'Destroys a stack using swarmpit'
author: 'First & Third'
branding:
  icon: cloud-off
  color: red
inputs:
  url:
    required: true
    description: 'URL of your swarmpit instance'
  api-key:
    required: true
    description: 'Swarmpit api key, you can get this from the swarmpit admin'
  stack:
    required: true
    description: 'Name of the stack you want destroyed'
runs:
  using: 'node16'
  main: 'dist/index.js'